### ISSUE TITLE
Titulo do forúm

### ISSUE THREAD

**Issue by serlus** [pythonprobr/curso-django#1054]
Oi Renzo, o título do forúm não corresponde com o do vídeo. O link da página no video redireciona para o tópico no forum para objetos pythonicos. 

[vídeo](https://www.python.pro.br/modulos/django/topicos/deploy-automatico)

[forum](https://forum.python.pro.br/t/objetos-pythonicos-funcao-anonima/451/3)

**Comment by renzon** [comment]
Consertado, obrigado por apontar o erro!
